Revenue := SUM(FactTicketSales[Revenue])
Tickets := COUNTROWS(FactTicketSales)
Avg Ticket Price := DIVIDE([Revenue],[Tickets])
Fees := SUM(FactTicketSales[Fees])
Discounts := SUM(FactTicketSales[Discount])
Net Revenue := [Revenue] - [Discounts] + [Fees]
Attendance := SUM(FactAttendance[ScannedCount])
No Shows := SUM(FactAttendance[NoShowCount])
Attendance Rate := DIVIDE([Attendance],[Attendance] + [No Shows])
Renewal Accounts := DISTINCTCOUNT(FactRenewals[AccountId])
Renewed Accounts := CALCULATE([Renewal Accounts], FactRenewals[RenewedFlag] = TRUE())
Renewal Rate := DIVIDE([Renewed Accounts],[Renewal Accounts])
Renewal Amount := SUM(FactRenewals[RenewalAmount])
Revenue LY := CALCULATE([Revenue], DATEADD(DimDate[Date], -1, YEAR))
Revenue YoY % := DIVIDE([Revenue]-[Revenue LY], [Revenue LY])
Revenue MTD := TOTALMTD([Revenue], DimDate[Date])
Revenue MTD LY := CALCULATE([Revenue MTD], DATEADD(DimDate[Date], -1, YEAR))
Revenue MTD YoY % := DIVIDE([Revenue MTD]-[Revenue MTD LY],[Revenue MTD LY])
Attendance MTD := TOTALMTD([Attendance], DimDate[Date])
Avg Weeknight Price := CALCULATE([Avg Ticket Price], DimGame[DayType] = "Weeknight")
Underpriced Weeknight Flag := IF(SELECTEDVALUE(DimGame[DayType]) = "Weeknight" && [Avg Ticket Price] < [Avg Weeknight Price] * 0.9, 1, 0)
Forecast Attendance (8wk) := CALCULATE(SUM(FactForecast[ForecastValue]), FactForecast[Metric] = "Attendance")
Forecast Revenue (8wk) := CALCULATE(SUM(FactForecast[ForecastValue]), FactForecast[Metric] = "Revenue")
MAPE Attendance := VAR a=[Attendance] VAR f=[Forecast Attendance (8wk)] RETURN IF(NOT ISBLANK(a)&&a<>0, ABS((a-f)/a), BLANK())
Revenue by Territory := SUMX(VALUES(DimSalesTerritory[TerritoryId]), [Revenue])
New Buyers := CALCULATE(DISTINCTCOUNT(FactTicketSales[CustomerId]), DimDate[Year] = MIN(DimDate[Year]))
Multi-Game Buyers := CALCULATE(DISTINCTCOUNT(FactTicketSales[CustomerId]), FILTER(VALUES(FactTicketSales[CustomerId]), CALCULATE([Tickets]) > 2))
Plan Buyers := CALCULATE(DISTINCTCOUNT(FactRenewals[AccountId]), NOT ISBLANK(FactRenewals[PlanId]))